//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCRUDMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int id_persona { get; set; }
        public string nombre_per { get; set; }
        public int edad_per { get; set; }
    }
}
